version: '3'

services:
  db:
    container_name: cashback_postgres
    image: postgres
    env_file: .env
    restart: unless-stopped
    volumes:
      - .:/usr/src/data
    environment:
      - POSTGRES_USER=$TYPEORM_USERNAME
      - POSTGRES_PASSWORD=$TYPEORM_PASSWORD
      - POSTGRES_DB=$TYPEORM_DATABASE
    ports:
      - '$TYPEORM_PORT:$TYPEORM_PORT'
  api:
    container_name: cashback_api
    restart: always
    build: .
    ports:
      - "3333:3333"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app